### ISSUE TITLE
自定义图片同步的方法添加到全局可配置的选项

### ISSUE THREAD

**Issue by Blue-FatMan** [liuqiao1995/luckysheet_django#1]
由于websocket无法发送较大数据限制，可否把图片的同步方式另外添加一个全局可选配置，提供用户自定义的同步方法

**Comment by Blue-FatMan** [comment]
该commit解决了这个问题https://github.com/liuqiao1995/luckysheet_django/commit/4e8bc55d6cd25b96ae6b07f12a28a20b616baed8

**Comment by liuqiao1995** [comment]
https://github.com/liuqiao1995/luckysheet_django/commit/4e8bc55d6cd25b96ae6b07f12a28a20b616baed8
